### ISSUE TITLE
Show Expired Licenses

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/donkey#38]
To help avoid confusion we should show expired ThemeForest licenses but disable them so they cannot be used.

**Comment by jakecaputo** [comment]
💯

**Comment by adampickering** [comment]
Hey hey! Can David @turtlepod  help out this @spencerfinnell ? I see this as a huge support pack purchase increase for us because will finally understand that they simply need to renew their support.

Instead of @FernandoSalinas33 getting comments like this on TF:

"So every time I try to login to submit a support ticket, it doesn’t work. I’m able to log in to my account on Astoundify, but I can’t get past the page where it asks for the license and my email. Not sure what I need to do here…?"

I'd like this to be added asap.

Messaging should be something like "Listify Theme Support License Has Expired Please Renew." with a link somewhere to go:

Marketify: https://themeforest.net/item_support/pricing_modal/6570786
Listify: https://themeforest.net/item_support/pricing_modal/5247604
Jobify: https://themeforest.net/item_support/pricing_modal/9602611

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/donkey/blob/master/src/inc/class-gravityforms.php#L63-L65

That check needs to be removed and all returned licenses added. Expired items should have dropdown values prefixed with `expired-` instead of `valid-`

Then another Gravity Form field should conditionally show if an option with `expired-` is chosen.

@turtlepod I've attached our Gravity Form that has the current logic.

Needs:

Gravity Forms
https://github.com/Astoundify/donkey
https://github.com/Astoundify/edd-envato-login

Visit "Settings > Donkey" and add Gravity Form ID and then add that ID to a page. 

So the Gravity Form license selection dropdown would output something like https://cloudup.com/cyarv4gqS6x

**Comment by turtlepod** [comment]
I don't know how to properly test this. I don't have any of you license or user data to test this.
I also don't know what i should input in "Product Whitelist" settings (or other settings).

But I hope this works https://github.com/Astoundify/donkey/commit/f845256f4ef4f7f8d79f6456e97cff1b0042f510

(Sorry, I accidentally push on "master" branch, do I need to revert and create branch for this?)

**Comment by adampickering** [comment]
Update, links should be:

Jobify: https://themeforest.net/checkout/from_item/9602611?license=regular&size=source&support=renew_6month

Listify: https://themeforest.net/checkout/from_item/5247604?license=regular&size=source&support=renew_6month

Marketify: https://themeforest.net/checkout/from_item/6570786?license=regular&size=source&support=renew_6month

**Comment by spencerfinnell** [comment]
Thanks @turtlepod -- master is fine and will test soon.

@adampickering That will need to be set up in a conditional field in Gravity Forms. You can test the updates on the sandbox site.

**Comment by adampickering** [comment]
hey @spencerfinnell can you test this Tuesday? tomorrow?

**Comment by adampickering** [comment]
Hey @spencerfinnell or @turtlepod can we get to this, this week?

**Comment by spencerfinnell** [comment]
@adampickering That will need to be set up in a conditional field in Gravity Forms. You can test the updates on the sandbox site.

**Comment by adampickering** [comment]
What happened with this? @spencerfinnell

**Comment by spencerfinnell** [comment]
It's live: https://cloudup.com/cN5fFII8cfD

**Comment by adampickering** [comment]
Hmm how about displaying themes being expired? Can we show the links to re-sub? 

Jobify: https://themeforest.net/checkout/from_item/9602611?license=regular&size=source&support=renew_6month

Listify: https://themeforest.net/checkout/from_item/5247604?license=regular&size=source&support=renew_6month

Marketify: https://themeforest.net/checkout/from_item/6570786?license=regular&size=source&support=renew_6month

**Comment by spencerfinnell** [comment]
Themes will show the same way. They will have a value of `expired-{$item-name}` if you want to set up conditional fields in GF: https://astoundify.com/wp-admin/admin.php?page=gf_edit_forms&id=1
